spring:
  application:
    name: FoodAPI

  datasource:
    url: jdbc:mysql://localhost:3306/foodapi
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

resilience4j.ratelimiter:
  instances:
    foodApiLimiter:
      limitForPeriod: 2
      limitRefreshPeriod: 10s
      timeoutDuration: 0